#database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventoryDb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: ${mysql.pass}
  main:
    allow-circular-references: true
  jpa:
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
  application:
    name: inventory-service


#Zipkin config
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1.0

#Port
server:
  port: 9004

#eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



